import 'package:avatar_plus/avatar_plus.dart';
import 'package:flutter/material.dart';
import 'package:uniun/core/theme/app_theme.dart';

/// Profile avatar widget.
///
/// Default: deterministic illustration generated by `avatar_plus` from the
/// user's npub seed. Once the user types a display name, the illustration
/// updates to one seeded from that name so it feels more personal.
///
/// The camera overlay button is reserved for future Blossom photo upload.
/// If [photoUrl] is provided (e.g. after the user uploads a photo), the
/// network image is shown instead of the generated illustration.
class GeneratedAvatar extends StatelessWidget {
  const GeneratedAvatar({
    super.key,
    required this.seed,
    required this.name,
    this.photoUrl,
    this.size = 96,
  });

  /// npub or any stable identifier — used when [name] is empty.
  final String seed;

  /// Display name typed by the user — takes over as the seed once non-empty.
  final String name;

  /// Optional network photo URL — shown instead of the generated avatar.
  final String? photoUrl;

  /// Diameter of the avatar circle.
  final double size;

  @override
  Widget build(BuildContext context) {
    // Use the display name as seed once the user starts typing so the
    // illustration immediately reflects their identity.
    final avatarSeed = name.trim().isNotEmpty ? name.trim() : seed;

    return Stack(
      alignment: Alignment.center,
      children: [
        // ── Avatar circle ───────────────────────────────────────────────
        Container(
          width: size,
          height: size,
          decoration: BoxDecoration(
            shape: BoxShape.circle,
            border: Border.all(
              color: AppColors.outlineVariant.withValues(alpha: 0.35),
              width: 1.5,
            ),
          ),
          clipBehavior: Clip.antiAlias,
          child: photoUrl != null
              ? Image.network(
                  photoUrl!,
                  fit: BoxFit.cover,
                  errorBuilder: (_, __, ___) => _generatedAvatar(avatarSeed),
                )
              : _generatedAvatar(avatarSeed),
        ),

        // ── Camera overlay — tap to upload (TODO: Blossom) ─────────────
        Positioned(
          bottom: 0,
          right: 0,
          child: GestureDetector(
            onTap: () {
              // TODO: image_picker → Blossom upload
            },
            child: Container(
              width: 28,
              height: 28,
              decoration: BoxDecoration(
                color: AppColors.surface,
                shape: BoxShape.circle,
                border: Border.all(
                  color: AppColors.primary.withValues(alpha: 0.3),
                  width: 1.5,
                ),
                boxShadow: [
                  BoxShadow(
                    color: Colors.black.withValues(alpha: 0.08),
                    blurRadius: 4,
                  ),
                ],
              ),
              child: const Icon(
                Icons.add_a_photo_rounded,
                size: 13,
                color: AppColors.primary,
              ),
            ),
          ),
        ),
      ],
    );
  }

  Widget _generatedAvatar(String avatarSeed) {
    return AvatarPlus(
      avatarSeed.isEmpty ? 'uniun' : avatarSeed,
      width: size,
      height: size,
      trBackground: false,
    );
  }
}
